/* Original scene vocabulary and contextual examples. Stable IDs preserve learning records. */
var SCENE_VOCAB = [
  {
    "sceneId": "restaurant",
    "word": "人数",
    "reading": "にんずう",
    "meaning": "人数",
    "type": "名",
    "level": "n4",
    "ex_jp": "予約の人数を四人から五人に変更したいです。",
    "ex_read": "よやくのにんずうをよにんからごにんにへんこうしたいです。",
    "ex_cn": "我想把预订人数从四人改成五人。",
    "id": 20001,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "禁煙席",
    "reading": "きんえんせき",
    "meaning": "禁烟座位",
    "type": "名",
    "level": "n4",
    "ex_jp": "禁煙席が空くまで待ちます。",
    "ex_read": "きんえんせきがあくまでまちます。",
    "ex_cn": "我等到禁烟座位空出来。",
    "id": 20002,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "おすすめ",
    "reading": "おすすめ",
    "meaning": "推荐；推荐的菜品",
    "type": "名",
    "level": "n4",
    "ex_jp": "魚料理なら、今日のおすすめは何ですか。",
    "ex_read": "さかなりょうりなら、きょうのおすすめはなんですか。",
    "ex_cn": "如果点鱼类菜肴，今天推荐什么？",
    "id": 20003,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "定食",
    "reading": "ていしょく",
    "meaning": "套餐；定食",
    "type": "名",
    "level": "n4",
    "ex_jp": "焼き魚の定食には、みそ汁が付きますか。",
    "ex_read": "やきざかなのていしょくには、みそしるがつきますか。",
    "ex_cn": "烤鱼套餐配味噌汤吗？",
    "id": 20004,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "日替わり",
    "reading": "ひがわり",
    "meaning": "每日更换；每日特餐",
    "type": "名",
    "level": "n3",
    "ex_jp": "日替わりのランチはもう売り切れだそうです。",
    "ex_read": "ひがわりのらんちはもううりきれだそうです。",
    "ex_cn": "听说今日午餐特餐已经卖完了。",
    "id": 20005,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "取り分ける",
    "reading": "とりわける",
    "meaning": "分到各自的盘子里",
    "type": "动",
    "level": "n3",
    "ex_jp": "子どもの分を先に取り分けてもいいですか。",
    "ex_read": "こどものぶんをさきにとりわけてもいいですか。",
    "ex_cn": "可以先把孩子吃的那份分出来吗？",
    "id": 20006,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "おかわり",
    "reading": "おかわり",
    "meaning": "再来一份；添饭或续饮",
    "type": "名",
    "level": "n4",
    "ex_jp": "ご飯のおかわりは無料ですか。",
    "ex_read": "ごはんのおかわりはむりょうですか。",
    "ex_cn": "添饭免费吗？",
    "id": 20007,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "別々",
    "reading": "べつべつ",
    "meaning": "分开；各自",
    "type": "名・形动",
    "level": "n4",
    "ex_jp": "会計は別々でお願いします。",
    "ex_read": "かいけいはべつべつでおねがいします。",
    "ex_cn": "请帮我们分开结账。",
    "id": 20008,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "会計",
    "reading": "かいけい",
    "meaning": "结账；账款",
    "type": "名",
    "level": "n4",
    "ex_jp": "会計は席でできますか。",
    "ex_read": "かいけいはせきでできますか。",
    "ex_cn": "可以在座位上结账吗？",
    "id": 20009,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "restaurant",
    "word": "抜き",
    "reading": "ぬき",
    "meaning": "去掉；不加",
    "type": "名",
    "level": "n3",
    "ex_jp": "このうどんは、ねぎ抜きでお願いできますか。",
    "ex_read": "このうどんは、ねぎぬきでおねがいできますか。",
    "ex_cn": "这份乌冬面可以不放葱吗？",
    "id": 20010,
    "topicId": "food",
    "category": "餐厅点餐",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "店内",
    "reading": "てんない",
    "meaning": "店内；堂食",
    "type": "名",
    "level": "n4",
    "ex_jp": "店内で飲む場合も、同じ値段ですか。",
    "ex_read": "てんないでのむばあいも、おなじねだんですか。",
    "ex_cn": "在店里喝也是同样的价格吗？",
    "id": 20011,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "持ち帰り",
    "reading": "もちかえり",
    "meaning": "外带；打包带走",
    "type": "名",
    "level": "n4",
    "ex_jp": "コーヒー二つ、持ち帰りでお願いします。",
    "ex_read": "こーひーふたつ、もちかえりでおねがいします。",
    "ex_cn": "两杯咖啡，请帮我打包。",
    "id": 20012,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "氷抜き",
    "reading": "こおりぬき",
    "meaning": "不加冰",
    "type": "名",
    "level": "n3",
    "ex_jp": "アイスティーを氷抜きで一つください。",
    "ex_read": "あいすてぃーをこおりぬきでひとつください。",
    "ex_cn": "请给我一杯不加冰的冰红茶。",
    "id": 20013,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "甘さ",
    "reading": "あまさ",
    "meaning": "甜度；甜味",
    "type": "名",
    "level": "n4",
    "ex_jp": "この飲み物は甘さを調整できますか。",
    "ex_read": "こののみものはあまさをちょうせいできますか。",
    "ex_cn": "这款饮料可以调整甜度吗？",
    "id": 20014,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "追加",
    "reading": "ついか",
    "meaning": "追加；加点",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "エスプレッソを一杯追加すると、いくらですか。",
    "ex_read": "えすぷれっそをいっぱいついかすると、いくらですか。",
    "ex_cn": "加一份浓缩咖啡要多少钱？",
    "id": 20015,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "豆乳",
    "reading": "とうにゅう",
    "meaning": "豆奶；豆浆",
    "type": "名",
    "level": "n3",
    "ex_jp": "牛乳を豆乳に変更してください。",
    "ex_read": "ぎゅうにゅうをとうにゅうにへんこうしてください。",
    "ex_cn": "请把牛奶换成豆奶。",
    "id": 20016,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "無糖",
    "reading": "むとう",
    "meaning": "无糖",
    "type": "名",
    "level": "n3",
    "ex_jp": "無糖のカフェラテはありますか。",
    "ex_read": "むとうのかふぇらてはありますか。",
    "ex_cn": "有不加糖的拿铁吗？",
    "id": 20017,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "空席",
    "reading": "くうせき",
    "meaning": "空座位",
    "type": "名",
    "level": "n3",
    "ex_jp": "二階に空席があれば、そこで飲みたいです。",
    "ex_read": "にかいにくうせきがあれば、そこでのみたいです。",
    "ex_cn": "如果二楼有空位，我想在那里喝。",
    "id": 20018,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "電源",
    "reading": "でんげん",
    "meaning": "电源；可供充电的插座",
    "type": "名",
    "level": "n3",
    "ex_jp": "電源の使える席はどこですか。",
    "ex_read": "でんげんのつかえるせきはどこですか。",
    "ex_cn": "哪里有可以使用电源的座位？",
    "id": 20019,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cafe",
    "word": "注文番号",
    "reading": "ちゅうもんばんごう",
    "meaning": "订单号码；取餐号",
    "type": "名",
    "level": "n3",
    "ex_jp": "注文番号が呼ばれたら、カウンターで受け取ってください。",
    "ex_read": "ちゅうもんばんごうがよばれたら、かうんたーでうけとってください。",
    "ex_cn": "叫到取餐号后，请到柜台领取。",
    "id": 20020,
    "topicId": "food",
    "category": "咖啡店",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "売り場",
    "reading": "うりば",
    "meaning": "售卖区；柜台",
    "type": "名",
    "level": "n4",
    "ex_jp": "豆腐の売り場は、野菜の隣です。",
    "ex_read": "とうふのうりばは、やさいのとなりです。",
    "ex_cn": "豆腐的售卖区在蔬菜旁边。",
    "id": 20021,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "量り売り",
    "reading": "はかりうり",
    "meaning": "按重量出售；称重销售",
    "type": "名",
    "level": "n3",
    "ex_jp": "このサラダは量り売りなので、少しだけ買えます。",
    "ex_read": "このさらだははかりうりなので、すこしだけかえます。",
    "ex_cn": "这款沙拉按重量卖，可以只买一点。",
    "id": 20022,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "見切り品",
    "reading": "みきりひん",
    "meaning": "清仓减价商品；临期折价商品",
    "type": "名",
    "level": "n2",
    "ex_jp": "今日食べるパンを、見切り品の棚で探しました。",
    "ex_read": "きょうたべるぱんを、みきりひんのたなでさがしました。",
    "ex_cn": "我在折价商品货架上找了今天要吃的面包。",
    "id": 20023,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "消費期限",
    "reading": "しょうひきげん",
    "meaning": "食用期限；保质安全期限",
    "type": "名",
    "level": "n3",
    "ex_jp": "お弁当を買う前に、消費期限を確認しました。",
    "ex_read": "おべんとうをかうまえに、しょうひきげんをかくにんしました。",
    "ex_cn": "买便当前，我确认了食用期限。",
    "id": 20024,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "賞味期限",
    "reading": "しょうみきげん",
    "meaning": "最佳赏味期限",
    "type": "名",
    "level": "n3",
    "ex_jp": "この缶詰の賞味期限は、来年の春までです。",
    "ex_read": "このかんづめのしょうみきげんは、らいねんのはるまでです。",
    "ex_cn": "这罐罐头的最佳赏味期限到明年春天。",
    "id": 20025,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "冷凍食品",
    "reading": "れいとうしょくひん",
    "meaning": "冷冻食品",
    "type": "名",
    "level": "n4",
    "ex_jp": "冷凍食品は、帰る直前にかごへ入れます。",
    "ex_read": "れいとうしょくひんは、かえるちょくぜんにかごへいれます。",
    "ex_cn": "冷冻食品我会在准备回家前才放进购物篮。",
    "id": 20026,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "値引き",
    "reading": "ねびき",
    "meaning": "降价；折价",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "閉店前に、残ったお総菜が値引きされました。",
    "ex_read": "へいてんまえに、のこったおそうざいがねびきされました。",
    "ex_cn": "关店前，剩下的熟食降价了。",
    "id": 20027,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "レジ袋",
    "reading": "れじぶくろ",
    "meaning": "购物塑料袋",
    "type": "名",
    "level": "n4",
    "ex_jp": "レジ袋は要りません。袋を持ってきました。",
    "ex_read": "れじぶくろはいりません。ふくろをもってきました。",
    "ex_cn": "不用购物袋，我自己带了袋子。",
    "id": 20028,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "ばら売り",
    "reading": "ばらうり",
    "meaning": "单个出售；拆开零售",
    "type": "名",
    "level": "n3",
    "ex_jp": "このりんごは、ばら売りもしていますか。",
    "ex_read": "このりんごは、ばらうりもしていますか。",
    "ex_cn": "这种苹果也可以单个买吗？",
    "id": 20029,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "supermarket",
    "word": "小分け",
    "reading": "こわけ",
    "meaning": "分成小份",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "肉は小分けにして冷凍すると便利です。",
    "ex_read": "にくはこわけにしてれいとうするとべんりです。",
    "ex_cn": "把肉分成小份冷冻起来很方便。",
    "id": 20030,
    "topicId": "shopping",
    "category": "超市采购",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "試着室",
    "reading": "しちゃくしつ",
    "meaning": "试衣间",
    "type": "名",
    "level": "n4",
    "ex_jp": "試着室に、この服を三着持って入ってもいいですか。",
    "ex_read": "しちゃくしつに、このふくをさんちゃくもってはいってもいいですか。",
    "ex_cn": "可以带这三件衣服进试衣间吗？",
    "id": 20031,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "丈",
    "reading": "たけ",
    "meaning": "衣长；裤长；长度",
    "type": "名",
    "level": "n3",
    "ex_jp": "このズボンは、丈が少し長いです。",
    "ex_read": "このずぼんは、たけがすこしながいです。",
    "ex_cn": "这条裤子的裤腿有点长。",
    "id": 20032,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "色違い",
    "reading": "いろちがい",
    "meaning": "同款不同颜色",
    "type": "名",
    "level": "n3",
    "ex_jp": "このシャツの色違いを見せてもらえますか。",
    "ex_read": "このしゃつのいろちがいをみせてもらえますか。",
    "ex_cn": "能让我看看这件衬衫的其他颜色吗？",
    "id": 20033,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "在庫",
    "reading": "ざいこ",
    "meaning": "库存",
    "type": "名",
    "level": "n3",
    "ex_jp": "このサイズは、ほかの店舗に在庫がありますか。",
    "ex_read": "このさいずは、ほかのてんぽにざいこがありますか。",
    "ex_cn": "其他门店有这个尺码的库存吗？",
    "id": 20034,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "取り寄せ",
    "reading": "とりよせ",
    "meaning": "调货；订货",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "取り寄せをお願いすると、何日ぐらいかかりますか。",
    "ex_read": "とりよせをおねがいすると、なんにちぐらいかかりますか。",
    "ex_cn": "如果请你们调货，大概需要几天？",
    "id": 20035,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "返品",
    "reading": "へんぴん",
    "meaning": "退货",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "未使用ですが、返品はできますか。",
    "ex_read": "みしようですが、へんぴんはできますか。",
    "ex_cn": "还没有用过，可以退货吗？",
    "id": 20036,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "交換",
    "reading": "こうかん",
    "meaning": "更换；换货",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "サイズが合わなかったので、交換したいです。",
    "ex_read": "さいずがあわなかったので、こうかんしたいです。",
    "ex_cn": "尺码不合适，我想换货。",
    "id": 20037,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "レシート",
    "reading": "れしーと",
    "meaning": "购物小票",
    "type": "名",
    "level": "n4",
    "ex_jp": "返品するときに必要なので、レシートを取っておきます。",
    "ex_read": "へんぴんするときにひつようなので、れしーとをとっておきます。",
    "ex_cn": "退货时需要用到，所以我会保留小票。",
    "id": 20038,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "保証書",
    "reading": "ほしょうしょ",
    "meaning": "保修凭证；保修卡",
    "type": "名",
    "level": "n3",
    "ex_jp": "保証書は箱の中に入っています。",
    "ex_read": "ほしょうしょははこのなかにはいっています。",
    "ex_cn": "保修卡在盒子里。",
    "id": 20039,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "shopping",
    "word": "支払い方法",
    "reading": "しはらいほうほう",
    "meaning": "付款方式",
    "type": "名",
    "level": "n4",
    "ex_jp": "注文した後でも、支払い方法を変更できますか。",
    "ex_read": "ちゅうもんしたあとでも、しはらいほうほうをへんこうできますか。",
    "ex_cn": "下单之后还可以更改付款方式吗？",
    "id": 20040,
    "topicId": "shopping",
    "category": "购物退换",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "改札口",
    "reading": "かいさつぐち",
    "meaning": "检票口；车站闸机口",
    "type": "名",
    "level": "n4",
    "ex_jp": "南側の改札口で待ち合わせましょう。",
    "ex_read": "みなみがわのかいさつぐちでまちあわせましょう。",
    "ex_cn": "我们在南侧检票口碰面吧。",
    "id": 20041,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "乗り場",
    "reading": "のりば",
    "meaning": "乘车处；站台",
    "type": "名",
    "level": "n4",
    "ex_jp": "空港行きの電車の乗り場は、ここで合っていますか。",
    "ex_read": "くうこうゆきのでんしゃののりばは、ここであっていますか。",
    "ex_cn": "去机场的电车是在这里乘坐吗？",
    "id": 20042,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "乗り換え",
    "reading": "のりかえ",
    "meaning": "换乘",
    "type": "名",
    "level": "n4",
    "ex_jp": "この電車なら、乗り換えなしで行けます。",
    "ex_read": "このでんしゃなら、のりかえなしでいけます。",
    "ex_cn": "坐这班电车的话，可以不换乘直接到达。",
    "id": 20043,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "快速",
    "reading": "かいそく",
    "meaning": "快速列车",
    "type": "名",
    "level": "n4",
    "ex_jp": "快速は、この駅には止まりません。",
    "ex_read": "かいそくは、このえきにはとまりません。",
    "ex_cn": "快速列车不停这一站。",
    "id": 20044,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "各駅停車",
    "reading": "かくえきていしゃ",
    "meaning": "各站停车的普通列车",
    "type": "名",
    "level": "n4",
    "ex_jp": "急いでいないので、各駅停車に乗ります。",
    "ex_read": "いそいでいないので、かくえきていしゃにのります。",
    "ex_cn": "我不赶时间，所以坐每站都停的普通列车。",
    "id": 20045,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "遅延",
    "reading": "ちえん",
    "meaning": "延误；晚点",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "遅延のため、到着が十分ほど遅れます。",
    "ex_read": "ちえんのため、とうちゃくがじゅっぷんほどおくれます。",
    "ex_cn": "因为列车晚点，我会晚到十分钟左右。",
    "id": 20046,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "運転見合わせ",
    "reading": "うんてんみあわせ",
    "meaning": "暂时停运",
    "type": "名",
    "level": "n3",
    "ex_jp": "大雨で運転見合わせとなり、バスで帰りました。",
    "ex_read": "おおあめでうんてんみあわせとなり、ばすでかえりました。",
    "ex_cn": "大雨导致列车暂时停运，我坐公交车回去了。",
    "id": 20047,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "終電",
    "reading": "しゅうでん",
    "meaning": "末班电车",
    "type": "名",
    "level": "n4",
    "ex_jp": "終電に間に合うように、そろそろ出ましょう。",
    "ex_read": "しゅうでんにまにあうように、そろそろでましょう。",
    "ex_cn": "为了赶上末班电车，我们差不多该出发了。",
    "id": 20048,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "往復",
    "reading": "おうふく",
    "meaning": "往返",
    "type": "名・动",
    "level": "n4",
    "ex_jp": "往復の切符を、まとめて買いたいです。",
    "ex_read": "おうふくのきっぷを、まとめてかいたいです。",
    "ex_cn": "我想把往返车票一起买好。",
    "id": 20049,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "station",
    "word": "チャージ",
    "reading": "ちゃーじ",
    "meaning": "充值",
    "type": "名・动",
    "level": "n4",
    "ex_jp": "改札に入る前に、カードにチャージします。",
    "ex_read": "かいさつにはいるまえに、かーどにちゃーじします。",
    "ex_cn": "进闸机前，我先给卡充值。",
    "id": 20050,
    "topicId": "travel",
    "category": "车站乘车",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "交差点",
    "reading": "こうさてん",
    "meaning": "交叉路口",
    "type": "名",
    "level": "n4",
    "ex_jp": "二つ目の交差点を右に曲がってください。",
    "ex_read": "ふたつめのこうさてんをみぎにまがってください。",
    "ex_cn": "请在第二个路口右转。",
    "id": 20051,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "横断歩道",
    "reading": "おうだんほどう",
    "meaning": "人行横道；斑马线",
    "type": "名",
    "level": "n4",
    "ex_jp": "横断歩道を渡ったところに、郵便局があります。",
    "ex_read": "おうだんほどうをわたったところに、ゆうびんきょくがあります。",
    "ex_cn": "过了人行横道就是邮局。",
    "id": 20052,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "突き当たり",
    "reading": "つきあたり",
    "meaning": "走到尽头的地方",
    "type": "名",
    "level": "n3",
    "ex_jp": "この道の突き当たりを左に曲がると、駅が見えます。",
    "ex_read": "このみちのつきあたりをひだりにまがると、えきがみえます。",
    "ex_cn": "沿这条路走到尽头左转，就能看到车站。",
    "id": 20053,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "目印",
    "reading": "めじるし",
    "meaning": "标志；认路的参照物",
    "type": "名",
    "level": "n3",
    "ex_jp": "角にある赤い看板が目印です。",
    "ex_read": "かどにあるあかいかんばんがめじるしです。",
    "ex_cn": "以拐角处的红色招牌为标志。",
    "id": 20054,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "遠回り",
    "reading": "とおまわり",
    "meaning": "绕远路",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "橋が工事中なので、少し遠回りになります。",
    "ex_read": "はしがこうじちゅうなので、すこしとおまわりになります。",
    "ex_cn": "桥正在施工，所以要稍微绕一点路。",
    "id": 20055,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "徒歩",
    "reading": "とほ",
    "meaning": "步行",
    "type": "名",
    "level": "n4",
    "ex_jp": "美術館までは、ここから徒歩で十五分ほどです。",
    "ex_read": "びじゅつかんまでは、ここからとほでじゅうごふんほどです。",
    "ex_cn": "从这里步行到美术馆大约需要十五分钟。",
    "id": 20056,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "右折",
    "reading": "うせつ",
    "meaning": "右转",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "次の信号で右折すると、駐車場の入口があります。",
    "ex_read": "つぎのしんごうでうせつすると、ちゅうしゃじょうのいりぐちがあります。",
    "ex_cn": "在下一个红绿灯处右转，就是停车场入口。",
    "id": 20057,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "左折",
    "reading": "させつ",
    "meaning": "左转",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "この道は狭いので、左折するときは気をつけてください。",
    "ex_read": "このみちはせまいので、させつするときはきをつけてください。",
    "ex_cn": "这条路很窄，左转时请注意。",
    "id": 20058,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "地下道",
    "reading": "ちかどう",
    "meaning": "地下通道",
    "type": "名",
    "level": "n3",
    "ex_jp": "雨が降っているので、地下道を通って駅に向かいます。",
    "ex_read": "あめがふっているので、ちかどうをとおってえきにむかいます。",
    "ex_cn": "下着雨，我走地下通道去车站。",
    "id": 20059,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "directions",
    "word": "現在地",
    "reading": "げんざいち",
    "meaning": "当前位置",
    "type": "名",
    "level": "n3",
    "ex_jp": "地図の赤い丸が現在地を示しています。",
    "ex_read": "ちずのあかいまるがげんざいちをしめしています。",
    "ex_cn": "地图上的红圈标出了当前位置。",
    "id": 20060,
    "topicId": "travel",
    "category": "问路出行",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "搭乗口",
    "reading": "とうじょうぐち",
    "meaning": "登机口",
    "type": "名",
    "level": "n3",
    "ex_jp": "搭乗口が変更になったので、案内板を確認しました。",
    "ex_read": "とうじょうぐちがへんこうになったので、あんないばんをかくにんしました。",
    "ex_cn": "登机口变更了，我查看了指示牌。",
    "id": 20061,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "搭乗券",
    "reading": "とうじょうけん",
    "meaning": "登机牌",
    "type": "名",
    "level": "n3",
    "ex_jp": "搭乗券をスマートフォンで提示してもいいですか。",
    "ex_read": "とうじょうけんをすまーとふぉんでていじしてもいいですか。",
    "ex_cn": "可以用手机出示登机牌吗？",
    "id": 20062,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "預け荷物",
    "reading": "あずけにもつ",
    "meaning": "托运行李",
    "type": "名",
    "level": "n3",
    "ex_jp": "預け荷物は、このカウンターで渡せばいいですか。",
    "ex_read": "あずけにもつは、このかうんたーでわたせばいいですか。",
    "ex_cn": "托运行李交到这个柜台就可以了吗？",
    "id": 20063,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "機内持ち込み",
    "reading": "きないもちこみ",
    "meaning": "随身带上飞机",
    "type": "名",
    "level": "n3",
    "ex_jp": "この大きさのかばんは、機内持ち込みができますか。",
    "ex_read": "このおおきさのかばんは、きないもちこみができますか。",
    "ex_cn": "这么大的包可以随身带上飞机吗？",
    "id": 20064,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "保安検査",
    "reading": "ほあんけんさ",
    "meaning": "安全检查；安检",
    "type": "名",
    "level": "n3",
    "ex_jp": "保安検査の前に、ポケットから鍵を出しました。",
    "ex_read": "ほあんけんさのまえに、ぽけっとからかぎをだしました。",
    "ex_cn": "安检前，我把钥匙从口袋里拿了出来。",
    "id": 20065,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "入国審査",
    "reading": "にゅうこくしんさ",
    "meaning": "入境审查",
    "type": "名",
    "level": "n3",
    "ex_jp": "入国審査では、滞在するホテルの名前を聞かれました。",
    "ex_read": "にゅうこくしんさでは、たいざいするほてるのなまえをきかれました。",
    "ex_cn": "入境审查时，工作人员问了我入住酒店的名字。",
    "id": 20066,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "税関",
    "reading": "ぜいかん",
    "meaning": "海关",
    "type": "名",
    "level": "n3",
    "ex_jp": "税関は、荷物を受け取った先にあります。",
    "ex_read": "ぜいかんは、にもつをうけとったさきにあります。",
    "ex_cn": "领完行李再往前走就是海关。",
    "id": 20067,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "申告",
    "reading": "しんこく",
    "meaning": "申报",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "この食品は、申告が必要ですか。",
    "ex_read": "このしょくひんは、しんこくがひつようですか。",
    "ex_cn": "这种食品需要申报吗？",
    "id": 20068,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "乗り継ぎ",
    "reading": "のりつぎ",
    "meaning": "转机；接续换乘",
    "type": "名",
    "level": "n3",
    "ex_jp": "乗り継ぎの時間が短いので、到着したらすぐに次の搭乗口に向かいます。",
    "ex_read": "のりつぎのじかんがみじかいので、とうちゃくしたらすぐにつぎのとうじょうぐちにむかいます。",
    "ex_cn": "转机时间很短，抵达后我会马上前往下一个登机口。",
    "id": 20069,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "airport",
    "word": "手荷物受取所",
    "reading": "てにもつうけとりじょ",
    "meaning": "行李领取处",
    "type": "名",
    "level": "n3",
    "ex_jp": "手荷物受取所で待っていましたが、スーツケースが出てきません。",
    "ex_read": "てにもつうけとりじょでまっていましたが、すーつけーすがでてきません。",
    "ex_cn": "我在行李领取处等了一会儿，但行李箱还没出来。",
    "id": 20070,
    "topicId": "travel",
    "category": "机场出入境",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "予約名",
    "reading": "よやくめい",
    "meaning": "预订人姓名；预订所用姓名",
    "type": "名",
    "level": "n4",
    "ex_jp": "予約名はチャンです。二泊で予約しました。",
    "ex_read": "よやくめいはちゃんです。にはくでよやくしました。",
    "ex_cn": "预订姓名是张，我订了两晚。",
    "id": 20071,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "宿泊",
    "reading": "しゅくはく",
    "meaning": "住宿",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "友人も同じホテルに宿泊する予定です。",
    "ex_read": "ゆうじんもおなじほてるにしゅくはくするよていです。",
    "ex_cn": "朋友也打算住在同一家酒店。",
    "id": 20072,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "素泊まり",
    "reading": "すどまり",
    "meaning": "不含餐的住宿",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "朝早く出発するので、素泊まりのプランにしました。",
    "ex_read": "あさはやくしゅっぱつするので、すどまりのぷらんにしました。",
    "ex_cn": "因为一大早就要出发，我选了不含餐的住宿方案。",
    "id": 20073,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "朝食付き",
    "reading": "ちょうしょくつき",
    "meaning": "含早餐",
    "type": "名",
    "level": "n4",
    "ex_jp": "この料金は、朝食付きですか。",
    "ex_read": "このりょうきんは、ちょうしょくつきですか。",
    "ex_cn": "这个价格包含早餐吗？",
    "id": 20074,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "連泊",
    "reading": "れんぱく",
    "meaning": "连续住宿多晚",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "連泊中の部屋の掃除は、毎日ありますか。",
    "ex_read": "れんぱくちゅうのへやのそうじは、まいにちありますか。",
    "ex_cn": "连续入住期间，房间每天都会打扫吗？",
    "id": 20075,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "空室",
    "reading": "くうしつ",
    "meaning": "空房；可入住的房间",
    "type": "名",
    "level": "n3",
    "ex_jp": "今夜、二人で泊まれる空室はありますか。",
    "ex_read": "こんや、ふたりでとまれるくうしつはありますか。",
    "ex_cn": "今晚有可以住两个人的空房吗？",
    "id": 20076,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "鍵",
    "reading": "かぎ",
    "meaning": "钥匙；房卡",
    "type": "名",
    "level": "n5",
    "ex_jp": "部屋に鍵を置いたまま、ドアを閉めてしまいました。",
    "ex_read": "へやにかぎをおいたまま、どあをしめてしまいました。",
    "ex_cn": "我把钥匙落在房间里，就把门关上了。",
    "id": 20077,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "延長",
    "reading": "えんちょう",
    "meaning": "延长",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "チェックアウトの時間を一時間延長できますか。",
    "ex_read": "ちぇっくあうとのじかんをいちじかんえんちょうできますか。",
    "ex_cn": "退房时间可以延后一小时吗？",
    "id": 20078,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "荷物を預ける",
    "reading": "にもつをあずける",
    "meaning": "寄存行李",
    "type": "表达",
    "level": "n4",
    "ex_jp": "チェックインの前に、荷物を預けてもいいですか。",
    "ex_read": "ちぇっくいんのまえに、にもつをあずけてもいいですか。",
    "ex_cn": "入住前可以先寄存行李吗？",
    "id": 20079,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hotel",
    "word": "領収書",
    "reading": "りょうしゅうしょ",
    "meaning": "收据；正式收款凭证",
    "type": "名",
    "level": "n3",
    "ex_jp": "会社名で領収書を出していただけますか。",
    "ex_read": "かいしゃめいでりょうしゅうしょをだしていただけますか。",
    "ex_cn": "可以开一张抬头为公司名称的收据吗？",
    "id": 20080,
    "topicId": "travel",
    "category": "酒店入住",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "内見",
    "reading": "ないけん",
    "meaning": "看房；参观房屋内部",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "週末に、この部屋の内見をしたいです。",
    "ex_read": "しゅうまつに、このへやのないけんをしたいです。",
    "ex_cn": "我想周末来看这间房。",
    "id": 20081,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "家賃",
    "reading": "やちん",
    "meaning": "房租",
    "type": "名",
    "level": "n4",
    "ex_jp": "家賃は、毎月何日までに払えばいいですか。",
    "ex_read": "やちんは、まいつきなんにちまでにはらえばいいですか。",
    "ex_cn": "房租每月最晚几号支付？",
    "id": 20082,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "敷金",
    "reading": "しききん",
    "meaning": "租房押金",
    "type": "名",
    "level": "n3",
    "ex_jp": "敷金は、退去するときにどのように精算されますか。",
    "ex_read": "しききんは、たいきょするときにどのようにせいさんされますか。",
    "ex_cn": "退房时，押金是怎么结算的？",
    "id": 20083,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "礼金",
    "reading": "れいきん",
    "meaning": "租房礼金；付给房东的签约费用",
    "type": "名",
    "level": "n3",
    "ex_jp": "できれば、礼金のない物件を探しています。",
    "ex_read": "できれば、れいきんのないぶっけんをさがしています。",
    "ex_cn": "如果可以的话，我想找不收礼金的房子。",
    "id": 20084,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "管理費",
    "reading": "かんりひ",
    "meaning": "管理费",
    "type": "名",
    "level": "n3",
    "ex_jp": "管理費は、家賃とは別にかかりますか。",
    "ex_read": "かんりひは、やちんとはべつにかかりますか。",
    "ex_cn": "管理费需要在房租之外另付吗？",
    "id": 20085,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "間取り",
    "reading": "まどり",
    "meaning": "户型；房间布局",
    "type": "名",
    "level": "n3",
    "ex_jp": "間取り図を見ると、台所と寝室は分かれています。",
    "ex_read": "まどりずをみると、だいどころとしんしつはわかれています。",
    "ex_cn": "从户型图看，厨房和卧室是分开的。",
    "id": 20086,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "入居",
    "reading": "にゅうきょ",
    "meaning": "入住；迁入住房",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "来月の初めに入居できる部屋はありますか。",
    "ex_read": "らいげつのはじめににゅうきょできるへやはありますか。",
    "ex_cn": "有下个月初就能入住的房子吗？",
    "id": 20087,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "退去",
    "reading": "たいきょ",
    "meaning": "退房；搬离租住房屋",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "退去する日が決まったので、管理会社に連絡しました。",
    "ex_read": "たいきょするひがきまったので、かんりがいしゃにれんらくしました。",
    "ex_cn": "搬离日期定下来后，我联系了管理公司。",
    "id": 20088,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "立ち会い",
    "reading": "たちあい",
    "meaning": "在场确认；陪同检查",
    "type": "名",
    "level": "n3",
    "ex_jp": "退去時の立ち会いは、平日でも大丈夫ですか。",
    "ex_read": "たいきょじのたちあいは、へいじつでもだいじょうぶですか。",
    "ex_cn": "退房时的现场检查安排在工作日也可以吗？",
    "id": 20089,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "housing",
    "word": "引っ越し",
    "reading": "ひっこし",
    "meaning": "搬家",
    "type": "名・动",
    "level": "n4",
    "ex_jp": "引っ越しの前に、使わない家具を処分しました。",
    "ex_read": "ひっこしのまえに、つかわないかぐをしょぶんしました。",
    "ex_cn": "搬家前，我处理掉了不用的家具。",
    "id": 20090,
    "topicId": "home",
    "category": "租房搬家",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "転入届",
    "reading": "てんにゅうとどけ",
    "meaning": "迁入申报",
    "type": "名",
    "level": "n3",
    "ex_jp": "転入届は、どの窓口で出せますか。",
    "ex_read": "てんにゅうとどけは、どのまどぐちでだせますか。",
    "ex_cn": "迁入申报可以在哪个窗口提交？",
    "id": 20091,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "転出届",
    "reading": "てんしゅつとどけ",
    "meaning": "迁出申报",
    "type": "名",
    "level": "n3",
    "ex_jp": "引っ越しが決まったので、転出届の出し方を調べました。",
    "ex_read": "ひっこしがきまったので、てんしゅつとどけのだしかたをしらべました。",
    "ex_cn": "确定要搬家后，我查了如何办理迁出申报。",
    "id": 20092,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "住民票",
    "reading": "じゅうみんひょう",
    "meaning": "住民票；居民登记记录",
    "type": "名",
    "level": "n3",
    "ex_jp": "住民票の写しを一通ください。",
    "ex_read": "じゅうみんひょうのうつしをいっつうください。",
    "ex_cn": "请给我开一份住民票副本。",
    "id": 20093,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "本人確認書類",
    "reading": "ほんにんかくにんしょるい",
    "meaning": "身份证明材料",
    "type": "名",
    "level": "n3",
    "ex_jp": "本人確認書類として、何を持ってくればいいですか。",
    "ex_read": "ほんにんかくにんしょるいとして、なにをもってくればいいですか。",
    "ex_cn": "作为身份证明，我需要带什么材料？",
    "id": 20094,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "在留カード",
    "reading": "ざいりゅうかーど",
    "meaning": "在留卡；外国居民居留证件",
    "type": "名",
    "level": "n3",
    "ex_jp": "在留カードの住所を変更したいです。",
    "ex_read": "ざいりゅうかーどのじゅうしょをへんこうしたいです。",
    "ex_cn": "我想变更在留卡上的地址。",
    "id": 20095,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "印鑑",
    "reading": "いんかん",
    "meaning": "印章",
    "type": "名",
    "level": "n3",
    "ex_jp": "この手続きに印鑑は必要ですか。",
    "ex_read": "このてつづきにいんかんはひつようですか。",
    "ex_cn": "办这项手续需要印章吗？",
    "id": 20096,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "窓口",
    "reading": "まどぐち",
    "meaning": "办事窗口；服务柜台",
    "type": "名",
    "level": "n4",
    "ex_jp": "窓口が混んでいたので、少し待ちました。",
    "ex_read": "まどぐちがこんでいたので、すこしまちました。",
    "ex_cn": "窗口办事的人很多，我等了一会儿。",
    "id": 20097,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "整理券",
    "reading": "せいりけん",
    "meaning": "排队号码票",
    "type": "名",
    "level": "n3",
    "ex_jp": "入口の機械で整理券を取ってください。",
    "ex_read": "いりぐちのきかいでせいりけんをとってください。",
    "ex_cn": "请在入口的机器上取号。",
    "id": 20098,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "申請書",
    "reading": "しんせいしょ",
    "meaning": "申请表；申请书",
    "type": "名",
    "level": "n3",
    "ex_jp": "申請書のこの欄には、何を書けばいいですか。",
    "ex_read": "しんせいしょのこのらんには、なにをかけばいいですか。",
    "ex_cn": "申请表的这一栏应该填什么？",
    "id": 20099,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "cityhall",
    "word": "記入例",
    "reading": "きにゅうれい",
    "meaning": "填写示例",
    "type": "名",
    "level": "n3",
    "ex_jp": "記入例を見ながら、住所と氏名を書きました。",
    "ex_read": "きにゅうれいをみながら、じゅうしょとしめいをかきました。",
    "ex_cn": "我参照填写示例，填上了地址和姓名。",
    "id": 20100,
    "topicId": "services",
    "category": "市役所办事",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "口座",
    "reading": "こうざ",
    "meaning": "银行账户",
    "type": "名",
    "level": "n3",
    "ex_jp": "給料を受け取るために、口座を開きたいです。",
    "ex_read": "きゅうりょうをうけとるために、こうざをひらきたいです。",
    "ex_cn": "我想开一个账户，用来收工资。",
    "id": 20101,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "残高",
    "reading": "ざんだか",
    "meaning": "余额",
    "type": "名",
    "level": "n3",
    "ex_jp": "支払う前に、口座の残高を確認しました。",
    "ex_read": "しはらうまえに、こうざのざんだかをかくにんしました。",
    "ex_cn": "付款前，我确认了账户余额。",
    "id": 20102,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "振り込み",
    "reading": "ふりこみ",
    "meaning": "转账；汇款",
    "type": "名",
    "level": "n3",
    "ex_jp": "振り込みが完了したら、控えを保存してください。",
    "ex_read": "ふりこみがかんりょうしたら、ひかえをほぞんしてください。",
    "ex_cn": "转账完成后，请保存凭条。",
    "id": 20103,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "引き落とし",
    "reading": "ひきおとし",
    "meaning": "从账户自动扣款",
    "type": "名",
    "level": "n3",
    "ex_jp": "家賃の引き落としは、毎月二十七日です。",
    "ex_read": "やちんのひきおとしは、まいつきにじゅうしちにちです。",
    "ex_cn": "我的房租每月二十七日自动扣款。",
    "id": 20104,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "手数料",
    "reading": "てすうりょう",
    "meaning": "手续费",
    "type": "名",
    "level": "n3",
    "ex_jp": "この時間に現金を下ろすと、手数料はかかりますか。",
    "ex_read": "このじかんにげんきんをおろすと、てすうりょうはかかりますか。",
    "ex_cn": "这个时间取现金会收手续费吗？",
    "id": 20105,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "暗証番号",
    "reading": "あんしょうばんごう",
    "meaning": "密码；个人识别码",
    "type": "名",
    "level": "n3",
    "ex_jp": "暗証番号を忘れてしまったのですが、どこで手続きできますか。",
    "ex_read": "あんしょうばんごうをわすれてしまったのですが、どこでてつづきできますか。",
    "ex_cn": "我忘记密码了，可以在哪里办理相关手续？",
    "id": 20106,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "限度額",
    "reading": "げんどがく",
    "meaning": "额度上限",
    "type": "名",
    "level": "n3",
    "ex_jp": "一日の引き出し限度額を知りたいです。",
    "ex_read": "いちにちのひきだしげんどがくをしりたいです。",
    "ex_cn": "我想知道每天最多能取多少钱。",
    "id": 20107,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "分割払い",
    "reading": "ぶんかつばらい",
    "meaning": "分期付款",
    "type": "名",
    "level": "n3",
    "ex_jp": "分割払いにすると、合計はいくらになりますか。",
    "ex_read": "ぶんかつばらいにすると、ごうけいはいくらになりますか。",
    "ex_cn": "如果分期付款，总共要付多少钱？",
    "id": 20108,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "一括払い",
    "reading": "いっかつばらい",
    "meaning": "一次性付款",
    "type": "名",
    "level": "n3",
    "ex_jp": "カードの一括払いでお願いします。",
    "ex_read": "かーどのいっかつばらいでおねがいします。",
    "ex_cn": "请用信用卡一次付清。",
    "id": 20109,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "bank",
    "word": "利用明細",
    "reading": "りようめいさい",
    "meaning": "使用明细；交易账单明细",
    "type": "名",
    "level": "n3",
    "ex_jp": "利用明細に、覚えのない支払いがありました。",
    "ex_read": "りようめいさいに、おぼえのないしはらいがありました。",
    "ex_cn": "账单明细上有一笔我不记得的付款。",
    "id": 20110,
    "topicId": "services",
    "category": "银行支付",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "宛先",
    "reading": "あてさき",
    "meaning": "收件地址；收件人信息",
    "type": "名",
    "level": "n3",
    "ex_jp": "宛先の住所に、部屋番号も書いてください。",
    "ex_read": "あてさきのじゅうしょに、へやばんごうもかいてください。",
    "ex_cn": "收件地址里也请写上房间号。",
    "id": 20111,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "差出人",
    "reading": "さしだしにん",
    "meaning": "寄件人；发件人",
    "type": "名",
    "level": "n3",
    "ex_jp": "差出人の欄には、自分の名前と住所を書きます。",
    "ex_read": "さしだしにんのらんには、じぶんのなまえとじゅうしょをかきます。",
    "ex_cn": "寄件人一栏填写自己的姓名和地址。",
    "id": 20112,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "郵便番号",
    "reading": "ゆうびんばんごう",
    "meaning": "邮政编码",
    "type": "名",
    "level": "n4",
    "ex_jp": "郵便番号を入力すると、住所の一部が表示されます。",
    "ex_read": "ゆうびんばんごうをにゅうりょくすると、じゅうしょのいちぶがひょうじされます。",
    "ex_cn": "输入邮政编码后，会显示部分地址。",
    "id": 20113,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "送り状",
    "reading": "おくりじょう",
    "meaning": "快递运单；托运单",
    "type": "名",
    "level": "n3",
    "ex_jp": "荷物を送るので、送り状を一枚ください。",
    "ex_read": "にもつをおくるので、おくりじょうをいちまいください。",
    "ex_cn": "我要寄包裹，请给我一张运单。",
    "id": 20114,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "送料",
    "reading": "そうりょう",
    "meaning": "运费；邮费",
    "type": "名",
    "level": "n3",
    "ex_jp": "この箱を大阪まで送ると、送料はいくらですか。",
    "ex_read": "このはこをおおさかまでおくると、そうりょうはいくらですか。",
    "ex_cn": "把这个箱子寄到大阪，运费是多少？",
    "id": 20115,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "着払い",
    "reading": "ちゃくばらい",
    "meaning": "运费到付",
    "type": "名",
    "level": "n3",
    "ex_jp": "相手の了承を得てから、着払いで送りました。",
    "ex_read": "あいてのりょうしょうをえてから、ちゃくばらいでおくりました。",
    "ex_cn": "征得对方同意后，我选择运费到付寄了出去。",
    "id": 20116,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "追跡番号",
    "reading": "ついせきばんごう",
    "meaning": "物流追踪号码；运单追踪号",
    "type": "名",
    "level": "n3",
    "ex_jp": "追跡番号で調べたら、荷物は配達中でした。",
    "ex_read": "ついせきばんごうでしらべたら、にもつははいたつちゅうでした。",
    "ex_cn": "用追踪号查询后发现，包裹正在派送。",
    "id": 20117,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "配達日時",
    "reading": "はいたつにちじ",
    "meaning": "送达日期和时间",
    "type": "名",
    "level": "n3",
    "ex_jp": "配達日時を、土曜日の午前中に変更したいです。",
    "ex_read": "はいたつにちじを、どようびのごぜんちゅうにへんこうしたいです。",
    "ex_cn": "我想把配送时间改成周六上午。",
    "id": 20118,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "不在票",
    "reading": "ふざいひょう",
    "meaning": "未能投递通知单",
    "type": "名",
    "level": "n3",
    "ex_jp": "帰宅すると、郵便受けに不在票が入っていました。",
    "ex_read": "きたくすると、ゆうびんうけにふざいひょうがはいっていました。",
    "ex_cn": "回家后，我发现信箱里有一张未能投递通知单。",
    "id": 20119,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "delivery",
    "word": "再配達",
    "reading": "さいはいたつ",
    "meaning": "再次投递；重新配送",
    "type": "名・动",
    "level": "n3",
    "ex_jp": "不在だったので、夕方の再配達をお願いしました。",
    "ex_read": "ふざいだったので、ゆうがたのさいはいたつをおねがいしました。",
    "ex_cn": "之前没人在家，所以我申请了傍晚再次配送。",
    "id": 20120,
    "topicId": "services",
    "category": "邮寄快递",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "授業の資料",
    "reading": "じゅぎょうのしりょう",
    "meaning": "课堂资料",
    "type": "名",
    "level": "n4",
    "ex_jp": "授業の資料は、学校のサイトからダウンロードできます。",
    "ex_read": "じゅぎょうのしりょうは、がっこうのサイトからダウンロードできます。",
    "ex_cn": "课堂资料可以从学校网站下载。",
    "id": 20121,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "板書",
    "reading": "ばんしょ",
    "meaning": "板书；黑板上写的内容",
    "type": "名",
    "level": "n3",
    "ex_jp": "先生が板書を消す前に、ノートに写しました。",
    "ex_read": "せんせいがばんしょをけすまえに、ノートにうつしました。",
    "ex_cn": "我在老师擦掉板书前，把内容抄到了笔记本上。",
    "id": 20122,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "提出期限",
    "reading": "ていしゅつきげん",
    "meaning": "提交截止日期",
    "type": "名",
    "level": "n3",
    "ex_jp": "レポートの提出期限を、手帳に書いておきます。",
    "ex_read": "レポートのていしゅつきげんを、てちょうにかいておきます。",
    "ex_cn": "我会把报告的提交截止日期先记在记事本上。",
    "id": 20123,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "聞き取る",
    "reading": "ききとる",
    "meaning": "听清；听懂所说的内容",
    "type": "动",
    "level": "n4",
    "ex_jp": "後ろの席では、先生の声がよく聞き取れません。",
    "ex_read": "うしろのせきでは、せんせいのこえがよくききとれません。",
    "ex_cn": "坐在后排不太能听清老师的声音。",
    "id": 20124,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "書き留める",
    "reading": "かきとめる",
    "meaning": "记下；笔录",
    "type": "动",
    "level": "n3",
    "ex_jp": "大切な説明だけ、短く書き留めました。",
    "ex_read": "たいせつなせつめいだけ、みじかくかきとめました。",
    "ex_cn": "我只把重要的说明简要记了下来。",
    "id": 20125,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "欠席届",
    "reading": "けっせきとどけ",
    "meaning": "缺席申请；请假条",
    "type": "名",
    "level": "n3",
    "ex_jp": "授業を休む場合は、欠席届が必要ですか。",
    "ex_read": "じゅぎょうをやすむばあいは、けっせきとどけがひつようですか。",
    "ex_cn": "如果要请假不上课，需要提交请假条吗？",
    "id": 20126,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "復習する",
    "reading": "ふくしゅうする",
    "meaning": "复习",
    "type": "动",
    "level": "n4",
    "ex_jp": "電車の中で、今日習った表現を復習しました。",
    "ex_read": "でんしゃのなかで、きょうならったひょうげんをふくしゅうしました。",
    "ex_cn": "我在电车上复习了今天学到的表达。",
    "id": 20127,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "授業についていく",
    "reading": "じゅぎょうについていく",
    "meaning": "跟上课程进度",
    "type": "表达",
    "level": "n3",
    "ex_jp": "専門用語が多くて、授業についていくのが大変です。",
    "ex_read": "せんもんようごがおおくて、じゅぎょうについていくのがたいへんです。",
    "ex_cn": "专业术语很多，跟上课程有些吃力。",
    "id": 20128,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "もう一度お願いします",
    "reading": "もういちどおねがいします",
    "meaning": "请再说一遍；请再来一次",
    "type": "表达",
    "level": "n5",
    "ex_jp": "すみません、最後の説明をもう一度お願いします。",
    "ex_read": "すみません、さいごのせつめいをもういちどおねがいします。",
    "ex_cn": "不好意思，最后那段说明请再讲一遍。",
    "id": 20129,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "classroom",
    "word": "ここまでで大丈夫ですか",
    "reading": "ここまででだいじょうぶですか",
    "meaning": "做到这里就可以了吗",
    "type": "表达",
    "level": "n4",
    "ex_jp": "先生、練習問題はここまでで大丈夫ですか。",
    "ex_read": "せんせい、れんしゅうもんだいはここまででだいじょうぶですか。",
    "ex_cn": "老师，练习题做到这里就可以了吗？",
    "id": 20130,
    "topicId": "study",
    "category": "课堂学习",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "出題範囲",
    "reading": "しゅつだいはんい",
    "meaning": "出题范围",
    "type": "名",
    "level": "n3",
    "ex_jp": "試験の出題範囲を、先生に確認しました。",
    "ex_read": "しけんのしゅつだいはんいを、せんせいにかくにんしました。",
    "ex_cn": "我向老师确认了考试的出题范围。",
    "id": 20131,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "過去問",
    "reading": "かこもん",
    "meaning": "历年试题",
    "type": "名",
    "level": "n3",
    "ex_jp": "週末は図書館で過去問を解く予定です。",
    "ex_read": "しゅうまつはとしょかんでかこもんをとくよていです。",
    "ex_cn": "我打算周末在图书馆做历年试题。",
    "id": 20132,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "解答用紙",
    "reading": "かいとうようし",
    "meaning": "答题纸；答题卡",
    "type": "名",
    "level": "n3",
    "ex_jp": "解答用紙に名前を書く欄が見つかりません。",
    "ex_read": "かいとうようしになまえをかくらんがみつかりません。",
    "ex_cn": "我找不到答题纸上填写姓名的地方。",
    "id": 20133,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "見直す",
    "reading": "みなおす",
    "meaning": "重新检查；复查",
    "type": "动",
    "level": "n4",
    "ex_jp": "提出する前に、答えをもう一度見直しました。",
    "ex_read": "ていしゅつするまえに、こたえをもういちどみなおしました。",
    "ex_cn": "交卷前，我又检查了一遍答案。",
    "id": 20134,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "時間配分",
    "reading": "じかんはいぶん",
    "meaning": "时间分配",
    "type": "名",
    "level": "n3",
    "ex_jp": "長文問題に時間を使いすぎたので、時間配分を変えます。",
    "ex_read": "ちょうぶんもんだいにじかんをつかいすぎたので、じかんはいぶんをかえます。",
    "ex_cn": "长篇阅读题花了太多时间，我要调整时间分配。",
    "id": 20135,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "記述問題",
    "reading": "きじゅつもんだい",
    "meaning": "需要书面作答的题目；问答题",
    "type": "名",
    "level": "n3",
    "ex_jp": "記述問題では、理由も自分の言葉で書きました。",
    "ex_read": "きじゅつもんだいでは、りゆうもじぶんのことばでかきました。",
    "ex_cn": "做问答题时，我也用自己的话写出了理由。",
    "id": 20136,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "受験票",
    "reading": "じゅけんひょう",
    "meaning": "准考证",
    "type": "名",
    "level": "n3",
    "ex_jp": "受験票を印刷して、かばんに入れました。",
    "ex_read": "じゅけんひょうをいんさつして、かばんにいれました。",
    "ex_cn": "我打印了准考证，放进了包里。",
    "id": 20137,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "合格発表",
    "reading": "ごうかくはっぴょう",
    "meaning": "合格结果公布；放榜",
    "type": "名",
    "level": "n3",
    "ex_jp": "合格発表の日は、学校のホームページで確認できます。",
    "ex_read": "ごうかくはっぴょうのひは、がっこうのホームページでかくにんできます。",
    "ex_cn": "可以在学校网站上查看公布合格结果的日期。",
    "id": 20138,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "間違い直し",
    "reading": "まちがいなおし",
    "meaning": "订正错题",
    "type": "名",
    "level": "n4",
    "ex_jp": "間違い直しをしてから、同じ問題をもう一度解きました。",
    "ex_read": "まちがいなおしをしてから、おなじもんだいをもういちどときました。",
    "ex_cn": "订正错题后，我又做了一遍同样的题。",
    "id": 20139,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "exam",
    "word": "模擬試験",
    "reading": "もぎしけん",
    "meaning": "模拟考试",
    "type": "名",
    "level": "n3",
    "ex_jp": "模擬試験の結果を見て、苦手な分野が分かりました。",
    "ex_read": "もぎしけんのけっかをみて、にがてなぶんやがわかりました。",
    "ex_cn": "看过模拟考试的结果后，我知道了自己的薄弱领域。",
    "id": 20140,
    "topicId": "study",
    "category": "备考应试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "志望動機",
    "reading": "しぼうどうき",
    "meaning": "应聘动机；申请理由",
    "type": "名",
    "level": "n3",
    "ex_jp": "面接では、志望動機を具体的に聞かれました。",
    "ex_read": "めんせつでは、しぼうどうきをぐたいてきにきかれました。",
    "ex_cn": "面试时，对方详细询问了我的应聘动机。",
    "id": 20141,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "職務経歴",
    "reading": "しょくむけいれき",
    "meaning": "工作经历",
    "type": "名",
    "level": "n2",
    "ex_jp": "これまでの職務経歴を、短く説明してください。",
    "ex_read": "これまでのしょくむけいれきを、みじかくせつめいしてください。",
    "ex_cn": "请简要介绍一下您至今的工作经历。",
    "id": 20142,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "自己紹介",
    "reading": "じこしょうかい",
    "meaning": "自我介绍",
    "type": "名",
    "level": "n4",
    "ex_jp": "自己紹介では、名前と今までの仕事について話しました。",
    "ex_read": "じこしょうかいでは、なまえといままでのしごとについてはなしました。",
    "ex_cn": "自我介绍时，我说了自己的姓名和此前的工作经历。",
    "id": 20143,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "採用担当者",
    "reading": "さいようたんとうしゃ",
    "meaning": "招聘负责人",
    "type": "名",
    "level": "n3",
    "ex_jp": "採用担当者から、面接の案内が届きました。",
    "ex_read": "さいようたんとうしゃから、めんせつのあんないがとどきました。",
    "ex_cn": "我收到了招聘负责人发来的面试通知。",
    "id": 20144,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "応募書類",
    "reading": "おうぼしょるい",
    "meaning": "应聘材料；申请材料",
    "type": "名",
    "level": "n3",
    "ex_jp": "応募書類に不足がないか、送信前に確認します。",
    "ex_read": "おうぼしょるいにふそくがないか、そうしんまえにかくにんします。",
    "ex_cn": "发送前，我会检查应聘材料是否齐全。",
    "id": 20145,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "面接日程",
    "reading": "めんせつにってい",
    "meaning": "面试安排；面试日期",
    "type": "名",
    "level": "n3",
    "ex_jp": "面接日程について、ご相談したいことがあります。",
    "ex_read": "めんせつにっていについて、ごそうだんしたいことがあります。",
    "ex_cn": "关于面试时间安排，我有件事想和您商量。",
    "id": 20146,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "強み",
    "reading": "つよみ",
    "meaning": "优势；长处",
    "type": "名",
    "level": "n3",
    "ex_jp": "私の強みは、相手の話を丁寧に聞けることです。",
    "ex_read": "わたしのつよみは、あいてのはなしをていねいにきけることです。",
    "ex_cn": "我的优势是能够认真倾听对方的话。",
    "id": 20147,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "勤務条件",
    "reading": "きんむじょうけん",
    "meaning": "工作条件；任职条件",
    "type": "名",
    "level": "n3",
    "ex_jp": "勤務条件について、もう少し詳しく教えていただけますか。",
    "ex_read": "きんむじょうけんについて、もうすこしくわしくおしえていただけますか。",
    "ex_cn": "能否再详细介绍一下工作条件？",
    "id": 20148,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "御社",
    "reading": "おんしゃ",
    "meaning": "贵公司（口语敬称）",
    "type": "名",
    "level": "n2",
    "ex_jp": "御社を志望した理由は、海外の仕事に関われるからです。",
    "ex_read": "おんしゃをしぼうしたりゆうは、かいがいのしごとにかかわれるからです。",
    "ex_cn": "我申请贵公司，是因为有机会参与海外业务。",
    "id": 20149,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "interview",
    "word": "差し支えなければ",
    "reading": "さしつかえなければ",
    "meaning": "如果方便的话；如果不介意的话",
    "type": "表达",
    "level": "n2",
    "ex_jp": "差し支えなければ、配属先の仕事内容を教えていただけますか。",
    "ex_read": "さしつかえなければ、はいぞくさきのしごとないようをおしえていただけますか。",
    "ex_cn": "如果方便的话，能否介绍一下拟分配部门的工作内容？",
    "id": 20150,
    "topicId": "work",
    "category": "求职面试",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "議題",
    "reading": "ぎだい",
    "meaning": "议题",
    "type": "名",
    "level": "n3",
    "ex_jp": "今日の議題を、先にメールで共有します。",
    "ex_read": "きょうのぎだいを、さきにメールできょうゆうします。",
    "ex_cn": "我会先通过邮件分享今天的议题。",
    "id": 20151,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "議事録",
    "reading": "ぎじろく",
    "meaning": "会议记录",
    "type": "名",
    "level": "n2",
    "ex_jp": "議事録には、決まったことと次の作業をまとめました。",
    "ex_read": "ぎじろくには、きまったこととつぎのさぎょうをまとめました。",
    "ex_cn": "我在会议记录中整理了已决定的事项和下一步工作。",
    "id": 20152,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "進捗状況",
    "reading": "しんちょくじょうきょう",
    "meaning": "进展情况",
    "type": "名",
    "level": "n2",
    "ex_jp": "各チームの進捗状況を、順番に確認しましょう。",
    "ex_read": "かくチームのしんちょくじょうきょうを、じゅんばんにかくにんしましょう。",
    "ex_cn": "我们依次确认一下各团队的进展情况吧。",
    "id": 20153,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "画面共有",
    "reading": "がめんきょうゆう",
    "meaning": "屏幕共享",
    "type": "名",
    "level": "n3",
    "ex_jp": "画面共有で、修正した部分をお見せします。",
    "ex_read": "がめんきょうゆうで、しゅうせいしたぶぶんをおみせします。",
    "ex_cn": "我通过屏幕共享给大家展示修改的部分。",
    "id": 20154,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "担当を決める",
    "reading": "たんとうをきめる",
    "meaning": "确定负责人；分配工作",
    "type": "表达",
    "level": "n3",
    "ex_jp": "作業を始める前に、それぞれの担当を決めましょう。",
    "ex_read": "さぎょうをはじめるまえに、それぞれのたんとうをきめましょう。",
    "ex_cn": "开始工作前，我们先确定各项工作的负责人吧。",
    "id": 20155,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "締め切りを延ばす",
    "reading": "しめきりをのばす",
    "meaning": "延长截止期限",
    "type": "表达",
    "level": "n3",
    "ex_jp": "確認に時間がかかるため、締め切りを延ばせますか。",
    "ex_read": "かくにんにじかんがかかるため、しめきりをのばせますか。",
    "ex_cn": "由于核对需要时间，可以延长截止期限吗？",
    "id": 20156,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "認識を合わせる",
    "reading": "にんしきをあわせる",
    "meaning": "统一认识；确认理解一致",
    "type": "表达",
    "level": "n2",
    "ex_jp": "今回の変更点について、認識を合わせたいです。",
    "ex_read": "こんかいのへんこうてんについて、にんしきをあわせたいです。",
    "ex_cn": "关于这次的修改内容，我想和大家确认一下理解是否一致。",
    "id": 20157,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "持ち帰って検討する",
    "reading": "もちかえってけんとうする",
    "meaning": "带回去研究；内部商议后再答复",
    "type": "表达",
    "level": "n2",
    "ex_jp": "そのご提案は、社内に持ち帰って検討します。",
    "ex_read": "そのごていあんは、しゃないにもちかえってけんとうします。",
    "ex_cn": "关于您的提议，我们会带回公司内部研究。",
    "id": 20158,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "日程調整",
    "reading": "にっていちょうせい",
    "meaning": "协调日期；协调时间安排",
    "type": "名",
    "level": "n3",
    "ex_jp": "次の会議の日程調整をお願いできますか。",
    "ex_read": "つぎのかいぎのにっていちょうせいをおねがいできますか。",
    "ex_cn": "可以请您协调一下下次会议的时间吗？",
    "id": 20159,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "meeting",
    "word": "補足する",
    "reading": "ほそくする",
    "meaning": "补充说明",
    "type": "动",
    "level": "n2",
    "ex_jp": "先ほどの説明について、少し補足してもよろしいですか。",
    "ex_read": "さきほどのせつめいについて、すこしほそくしてもよろしいですか。",
    "ex_cn": "关于刚才的说明，我可以稍作补充吗？",
    "id": 20160,
    "topicId": "work",
    "category": "会议协作",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "初めまして",
    "reading": "はじめまして",
    "meaning": "初次见面",
    "type": "表达",
    "level": "n5",
    "ex_jp": "初めまして。今日からこのクラスで勉強します。",
    "ex_read": "はじめまして。きょうからこのクラスでべんきょうします。",
    "ex_cn": "初次见面。我从今天起在这个班学习。",
    "id": 20161,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "お名前を伺ってもいいですか",
    "reading": "おなまえをうかがってもいいですか",
    "meaning": "可以请教您的姓名吗",
    "type": "表达",
    "level": "n3",
    "ex_jp": "失礼ですが、お名前を伺ってもいいですか。",
    "ex_read": "しつれいですが、おなまえをうかがってもいいですか。",
    "ex_cn": "冒昧问一下，可以请教您的姓名吗？",
    "id": 20162,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "呼び方",
    "reading": "よびかた",
    "meaning": "称呼方式；读法",
    "type": "名",
    "level": "n4",
    "ex_jp": "名前の呼び方が分からなかったので、本人に聞きました。",
    "ex_read": "なまえのよびかたがわからなかったので、ほんにんにききました。",
    "ex_cn": "我不知道该怎么读他的名字，就向本人询问了。",
    "id": 20163,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "出身地",
    "reading": "しゅっしんち",
    "meaning": "家乡；出生或成长的地方",
    "type": "名",
    "level": "n4",
    "ex_jp": "出身地は海の近くで、魚料理がおいしいです。",
    "ex_read": "しゅっしんちはうみのちかくで、さかなりょうりがおいしいです。",
    "ex_cn": "我的家乡靠近海边，鱼料理很好吃。",
    "id": 20164,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "お住まい",
    "reading": "おすまい",
    "meaning": "住所；居住的地方（敬称）",
    "type": "名",
    "level": "n4",
    "ex_jp": "お住まいは、この会場から近いですか。",
    "ex_read": "おすまいは、このかいじょうからちかいですか。",
    "ex_cn": "您住的地方离这个会场近吗？",
    "id": 20165,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "自営業",
    "reading": "じえいぎょう",
    "meaning": "个体经营；自己经营生意",
    "type": "名",
    "level": "n3",
    "ex_jp": "父は自営業で、小さな花屋を開いています。",
    "ex_read": "ちちはじえいぎょうで、ちいさなはなやをひらいています。",
    "ex_cn": "我父亲自己做生意，开了一家小花店。",
    "id": 20166,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "共通の知り合い",
    "reading": "きょうつうのしりあい",
    "meaning": "共同认识的人",
    "type": "名",
    "level": "n3",
    "ex_jp": "話してみると、共通の知り合いがいることが分かりました。",
    "ex_read": "はなしてみると、きょうつうのしりあいがいることがわかりました。",
    "ex_cn": "聊过之后，才发现我们有共同认识的人。",
    "id": 20167,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "こちらこそ",
    "reading": "こちらこそ",
    "meaning": "我才要……；彼此彼此",
    "type": "表达",
    "level": "n4",
    "ex_jp": "こちらこそ、お話しできてうれしかったです。",
    "ex_read": "こちらこそ、おはなしできてうれしかったです。",
    "ex_cn": "我也一样，很高兴能和您聊天。",
    "id": 20168,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "よろしくお願いします",
    "reading": "よろしくおねがいします",
    "meaning": "请多关照；拜托了",
    "type": "表达",
    "level": "n5",
    "ex_jp": "今日から一緒に働きます。よろしくお願いします。",
    "ex_read": "きょうからいっしょにはたらきます。よろしくおねがいします。",
    "ex_cn": "从今天起我们一起工作，请多关照。",
    "id": 20169,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "introduction",
    "word": "お会いできてうれしいです",
    "reading": "おあいできてうれしいです",
    "meaning": "很高兴能见到您",
    "type": "表达",
    "level": "n4",
    "ex_jp": "メールでは何度かお話ししましたが、お会いできてうれしいです。",
    "ex_read": "メールではなんどかおはなししましたが、おあいできてうれしいです。",
    "ex_cn": "虽然已经通过邮件交流过几次，能当面见到您还是很高兴。",
    "id": 20170,
    "topicId": "social",
    "category": "初次见面",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "都合がいい",
    "reading": "つごうがいい",
    "meaning": "时间方便；合适",
    "type": "表达",
    "level": "n4",
    "ex_jp": "来週の土曜日なら、午後のほうが都合がいいです。",
    "ex_read": "らいしゅうのどようびなら、ごごのほうがつごうがいいです。",
    "ex_cn": "如果是下周六，下午对我来说更方便。",
    "id": 20171,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "先約",
    "reading": "せんやく",
    "meaning": "事先的约定；已有的安排",
    "type": "名",
    "level": "n3",
    "ex_jp": "誘ってくれてありがとう。でも、その日は先約があります。",
    "ex_read": "さそってくれてありがとう。でも、そのひはせんやくがあります。",
    "ex_cn": "谢谢你邀请我，不过那天我已经有约了。",
    "id": 20172,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "日を改める",
    "reading": "ひをあらためる",
    "meaning": "改天；另选日期",
    "type": "表达",
    "level": "n3",
    "ex_jp": "今週は忙しそうなので、日を改めましょうか。",
    "ex_read": "こんしゅうはいそがしそうなので、ひをあらためましょうか。",
    "ex_cn": "你这周好像很忙，要不我们改天吧？",
    "id": 20173,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "待ち合わせ",
    "reading": "まちあわせ",
    "meaning": "约好见面；碰面",
    "type": "名",
    "level": "n4",
    "ex_jp": "待ち合わせの場所を、駅前のカフェに変えてもいいですか。",
    "ex_read": "まちあわせのばしょを、えきまえのカフェにかえてもいいですか。",
    "ex_cn": "可以把碰面的地点改到车站前的咖啡馆吗？",
    "id": 20174,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "手土産",
    "reading": "てみやげ",
    "meaning": "拜访时带的小礼物",
    "type": "名",
    "level": "n3",
    "ex_jp": "友人の家を訪ねるので、手土産にお菓子を買いました。",
    "ex_read": "ゆうじんのいえをたずねるので、てみやげにおかしをかいました。",
    "ex_cn": "因为要去朋友家做客，我买了点心当伴手礼。",
    "id": 20175,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "お邪魔します",
    "reading": "おじゃまします",
    "meaning": "打扰了（进入别人家等时使用）",
    "type": "表达",
    "level": "n4",
    "ex_jp": "お邪魔します。素敵なお部屋ですね。",
    "ex_read": "おじゃまします。すてきなおへやですね。",
    "ex_cn": "打扰了。您的房间真漂亮。",
    "id": 20176,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "お構いなく",
    "reading": "おかまいなく",
    "meaning": "请别费心；不用招待了",
    "type": "表达",
    "level": "n3",
    "ex_jp": "どうぞお構いなく。すぐに失礼しますので。",
    "ex_read": "どうぞおかまいなく。すぐにしつれいしますので。",
    "ex_cn": "请别费心了，我马上就告辞。",
    "id": 20177,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "ごちそうさまでした",
    "reading": "ごちそうさまでした",
    "meaning": "多谢款待；我吃好了",
    "type": "表达",
    "level": "n5",
    "ex_jp": "ごちそうさまでした。手作りのスープがとてもおいしかったです。",
    "ex_read": "ごちそうさまでした。てづくりのスープがとてもおいしかったです。",
    "ex_cn": "多谢款待。您亲手做的汤特别好喝。",
    "id": 20178,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "お招き",
    "reading": "おまねき",
    "meaning": "邀请（礼貌说法）",
    "type": "名",
    "level": "n3",
    "ex_jp": "今日はお招きいただき、ありがとうございます。",
    "ex_read": "きょうはおまねきいただき、ありがとうございます。",
    "ex_cn": "谢谢您今天邀请我来。",
    "id": 20179,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "invitation",
    "word": "また誘ってください",
    "reading": "またさそってください",
    "meaning": "下次请再邀请我",
    "type": "表达",
    "level": "n4",
    "ex_jp": "今回は参加できませんが、また誘ってください。",
    "ex_read": "こんかいはさんかできませんが、またさそってください。",
    "ex_cn": "这次我无法参加，不过下次请再叫上我。",
    "id": 20180,
    "topicId": "social",
    "category": "邀约做客",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "体験レッスン",
    "reading": "たいけんレッスン",
    "meaning": "体验课",
    "type": "名",
    "level": "n4",
    "ex_jp": "陶芸の体験レッスンで、小さな皿を作りました。",
    "ex_read": "とうげいのたいけんレッスンで、ちいさなさらをつくりました。",
    "ex_cn": "我在陶艺体验课上做了一个小盘子。",
    "id": 20181,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "見学する",
    "reading": "けんがくする",
    "meaning": "参观学习；观摩",
    "type": "动",
    "level": "n4",
    "ex_jp": "入会する前に、一度練習を見学できますか。",
    "ex_read": "にゅうかいするまえに、いちどれんしゅうをけんがくできますか。",
    "ex_cn": "正式加入前，可以先观摩一次练习吗？",
    "id": 20182,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "道具を借りる",
    "reading": "どうぐをかりる",
    "meaning": "借用工具或器材",
    "type": "表达",
    "level": "n4",
    "ex_jp": "会場で道具を借りられるので、手ぶらで参加できます。",
    "ex_read": "かいじょうでどうぐをかりられるので、てぶらでさんかできます。",
    "ex_cn": "现场可以借用器材，所以不用带装备也能参加。",
    "id": 20183,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "初心者向け",
    "reading": "しょしんしゃむけ",
    "meaning": "面向初学者；适合新手",
    "type": "名",
    "level": "n3",
    "ex_jp": "このコースは初心者向けで、基本から教えてもらえます。",
    "ex_read": "このコースはしょしんしゃむけで、きほんからおしえてもらえます。",
    "ex_cn": "这门课面向初学者，可以从基础开始学。",
    "id": 20184,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "参加費",
    "reading": "さんかひ",
    "meaning": "参加费用",
    "type": "名",
    "level": "n4",
    "ex_jp": "参加費には、材料代も含まれていますか。",
    "ex_read": "さんかひには、ざいりょうだいもふくまれていますか。",
    "ex_cn": "参加费里也包含材料费吗？",
    "id": 20185,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "持ち物",
    "reading": "もちもの",
    "meaning": "随身物品；需要携带的东西",
    "type": "名",
    "level": "n4",
    "ex_jp": "イベントの持ち物は、案内メールに書いてあります。",
    "ex_read": "イベントのもちものは、あんないメールにかいてあります。",
    "ex_cn": "活动需要携带的物品写在通知邮件里。",
    "id": 20186,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "予約制",
    "reading": "よやくせい",
    "meaning": "预约制",
    "type": "名",
    "level": "n3",
    "ex_jp": "この料理教室は予約制なので、先に申し込みました。",
    "ex_read": "このりょうりきょうしつはよやくせいなので、さきにもうしこみました。",
    "ex_cn": "这家烹饪教室实行预约制，所以我提前报了名。",
    "id": 20187,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "腕を上げる",
    "reading": "うでをあげる",
    "meaning": "技艺进步；提高本领",
    "type": "表达",
    "level": "n3",
    "ex_jp": "毎週練習しているだけあって、ずいぶん腕を上げましたね。",
    "ex_read": "まいしゅうれんしゅうしているだけあって、ずいぶんうでをあげましたね。",
    "ex_cn": "不愧是每周都在练习，你的技艺进步很大呢。",
    "id": 20188,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "趣味が合う",
    "reading": "しゅみがあう",
    "meaning": "兴趣相投",
    "type": "表达",
    "level": "n4",
    "ex_jp": "趣味が合う友達と、よく写真を撮りに行きます。",
    "ex_read": "しゅみがあうともだちと、よくしゃしんをとりにいきます。",
    "ex_cn": "我经常和兴趣相投的朋友一起去拍照。",
    "id": 20189,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "hobby",
    "word": "定期的に",
    "reading": "ていきてきに",
    "meaning": "定期地",
    "type": "表达",
    "level": "n3",
    "ex_jp": "このサークルでは、定期的に作品を見せ合っています。",
    "ex_read": "このサークルでは、ていきてきにさくひんをみせあっています。",
    "ex_cn": "这个社团会定期互相展示作品。",
    "id": 20190,
    "topicId": "leisure",
    "category": "兴趣活动",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "通信環境",
    "reading": "つうしんかんきょう",
    "meaning": "网络通信环境",
    "type": "名",
    "level": "n3",
    "ex_jp": "通信環境が安定している場所から参加します。",
    "ex_read": "つうしんかんきょうがあんていしているばしょからさんかします。",
    "ex_cn": "我会在网络连接稳定的地方参加。",
    "id": 20191,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "音声が途切れる",
    "reading": "おんせいがとぎれる",
    "meaning": "声音断断续续",
    "type": "表达",
    "level": "n3",
    "ex_jp": "音声が途切れて、最後の一言が聞こえませんでした。",
    "ex_read": "おんせいがとぎれて、さいごのひとことがきこえませんでした。",
    "ex_cn": "声音断了一下，最后一句我没听见。",
    "id": 20192,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "ミュートを解除する",
    "reading": "ミュートをかいじょする",
    "meaning": "解除静音",
    "type": "表达",
    "level": "n3",
    "ex_jp": "話す前に、ミュートを解除するのを忘れていました。",
    "ex_read": "はなすまえに、ミュートをかいじょするのをわすれていました。",
    "ex_cn": "我刚才说话前忘了解除静音。",
    "id": 20193,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "接続し直す",
    "reading": "せつぞくしなおす",
    "meaning": "重新连接",
    "type": "动",
    "level": "n3",
    "ex_jp": "画面が止まってしまったので、一度接続し直します。",
    "ex_read": "がめんがとまってしまったので、いちどせつぞくしなおします。",
    "ex_cn": "画面卡住了，我重新连接一下。",
    "id": 20194,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "添付ファイル",
    "reading": "てんぷファイル",
    "meaning": "附件",
    "type": "名",
    "level": "n3",
    "ex_jp": "添付ファイルが開けないので、別の形式で送っていただけますか。",
    "ex_read": "てんぷファイルがひらけないので、べつのけいしきでおくっていただけますか。",
    "ex_cn": "附件打不开，可以换一种格式发给我吗？",
    "id": 20195,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "既読",
    "reading": "きどく",
    "meaning": "已读",
    "type": "名",
    "level": "n3",
    "ex_jp": "既読になっていますが、まだ返事は来ていません。",
    "ex_read": "きどくになっていますが、まだへんじはきていません。",
    "ex_cn": "消息显示已读，不过还没有收到回复。",
    "id": 20196,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "誤送信",
    "reading": "ごそうしん",
    "meaning": "误发送；发错消息",
    "type": "名",
    "level": "n3",
    "ex_jp": "別のグループに誤送信してしまい、すぐに謝りました。",
    "ex_read": "べつのグループにごそうしんしてしまい、すぐにあやまりました。",
    "ex_cn": "我误发到了另一个群，立刻道了歉。",
    "id": 20197,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "通知設定",
    "reading": "つうちせってい",
    "meaning": "通知设置",
    "type": "名",
    "level": "n3",
    "ex_jp": "夜は音が鳴らないように、通知設定を変えました。",
    "ex_read": "よるはおとがならないように、つうちせっていをかえました。",
    "ex_cn": "我修改了通知设置，让它在晚上不发出提示音。",
    "id": 20198,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "グループチャット",
    "reading": "グループチャット",
    "meaning": "群聊",
    "type": "名",
    "level": "n4",
    "ex_jp": "集合場所の地図を、グループチャットに送りました。",
    "ex_read": "しゅうごうばしょのちずを、グループチャットにおくりました。",
    "ex_cn": "我把集合地点的地图发到了群聊里。",
    "id": 20199,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "online",
    "word": "返信が遅れる",
    "reading": "へんしんがおくれる",
    "meaning": "回复迟了；回复延迟",
    "type": "表达",
    "level": "n4",
    "ex_jp": "返信が遅れてすみません。予定を確認していました。",
    "ex_read": "へんしんがおくれてすみません。よていをかくにんしていました。",
    "ex_cn": "抱歉回复晚了，我刚才在确认日程。",
    "id": 20200,
    "topicId": "technology",
    "category": "线上沟通",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "初診",
    "reading": "しょしん",
    "meaning": "初诊；第一次就诊",
    "type": "名",
    "level": "n3",
    "ex_jp": "初診の予約を取りたいのですが、空いている日はありますか。",
    "ex_read": "しょしんのよやくをとりたいのですが、あいているひはありますか。",
    "ex_cn": "我想预约初诊，请问哪天有空位？",
    "id": 20201,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "再診",
    "reading": "さいしん",
    "meaning": "复诊；再次就诊",
    "type": "名",
    "level": "n3",
    "ex_jp": "再診の日時を忘れてしまったので、確認したいです。",
    "ex_read": "さいしんのにちじをわすれてしまったので、かくにんしたいです。",
    "ex_cn": "我忘了复诊的日期和时间，想确认一下。",
    "id": 20202,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "問診票",
    "reading": "もんしんひょう",
    "meaning": "问诊表",
    "type": "名",
    "level": "n3",
    "ex_jp": "問診票に、分からない言葉がいくつかあります。",
    "ex_read": "もんしんひょうに、わからないことばがいくつかあります。",
    "ex_cn": "问诊表上有几个词我不明白。",
    "id": 20203,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "診察券",
    "reading": "しんさつけん",
    "meaning": "就诊卡",
    "type": "名",
    "level": "n3",
    "ex_jp": "診察券を家に忘れてしまいました。",
    "ex_read": "しんさつけんをいえにわすれてしまいました。",
    "ex_cn": "我把就诊卡忘在家里了。",
    "id": 20204,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "予約変更",
    "reading": "よやくへんこう",
    "meaning": "更改预约",
    "type": "名",
    "level": "n4",
    "ex_jp": "予約変更は、電話でもできますか。",
    "ex_read": "よやくへんこうは、でんわでもできますか。",
    "ex_cn": "也可以通过电话更改预约吗？",
    "id": 20205,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "症状を伝える",
    "reading": "しょうじょうをつたえる",
    "meaning": "描述症状",
    "type": "表达",
    "level": "n3",
    "ex_jp": "緊張すると、症状をうまく伝えられません。",
    "ex_read": "きんちょうすると、しょうじょうをうまくつたえられません。",
    "ex_cn": "我一紧张，就无法很好地描述症状。",
    "id": 20206,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "受付時間",
    "reading": "うけつけじかん",
    "meaning": "受理时间；挂号时间",
    "type": "名",
    "level": "n4",
    "ex_jp": "午後の受付時間は、何時から何時までですか。",
    "ex_read": "ごごのうけつけじかんは、なんじからなんじまでですか。",
    "ex_cn": "下午的挂号时间是几点到几点？",
    "id": 20207,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "紹介状",
    "reading": "しょうかいじょう",
    "meaning": "介绍信；转诊信",
    "type": "名",
    "level": "n3",
    "ex_jp": "別の病院でもらった紹介状を持ってきました。",
    "ex_read": "べつのびょういんでもらったしょうかいじょうをもってきました。",
    "ex_cn": "我带来了另一家医院开的转诊信。",
    "id": 20208,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "付き添い",
    "reading": "つきそい",
    "meaning": "陪同；陪同的人",
    "type": "名",
    "level": "n3",
    "ex_jp": "今日は、母の付き添いで来ました。",
    "ex_read": "きょうは、ははのつきそいできました。",
    "ex_cn": "今天我是陪母亲来的。",
    "id": 20209,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "clinic",
    "word": "通訳をお願いする",
    "reading": "つうやくをおねがいする",
    "meaning": "请求口译协助",
    "type": "表达",
    "level": "n3",
    "ex_jp": "診察のとき、中国語の通訳をお願いできますか。",
    "ex_read": "しんさつのとき、ちゅうごくごのつうやくをおねがいできますか。",
    "ex_cn": "就诊时，可以请中文口译协助吗？",
    "id": 20210,
    "topicId": "health",
    "category": "挂号就诊",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "処方箋",
    "reading": "しょほうせん",
    "meaning": "处方",
    "type": "名",
    "level": "n3",
    "ex_jp": "この処方箋を、こちらで受け付けてもらえますか。",
    "ex_read": "このしょほうせんを、こちらでうけつけてもらえますか。",
    "ex_cn": "这里可以受理这张处方吗？",
    "id": 20211,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "お薬手帳",
    "reading": "おくすりてちょう",
    "meaning": "用药记录手册",
    "type": "名",
    "level": "n3",
    "ex_jp": "お薬手帳は、スマートフォンのアプリで管理しています。",
    "ex_read": "おくすりてちょうは、スマートフォンのアプリでかんりしています。",
    "ex_cn": "我通过手机应用管理用药记录手册。",
    "id": 20212,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "薬剤師",
    "reading": "やくざいし",
    "meaning": "药剂师",
    "type": "名",
    "level": "n3",
    "ex_jp": "薬剤師の方に、確認したいことがあります。",
    "ex_read": "やくざいしのかたに、かくにんしたいことがあります。",
    "ex_cn": "我有件事想向药剂师确认。",
    "id": 20213,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "飲み合わせ",
    "reading": "のみあわせ",
    "meaning": "药物合用的配伍关系",
    "type": "名",
    "level": "n3",
    "ex_jp": "今飲んでいる薬との飲み合わせについて、相談したいです。",
    "ex_read": "いまのんでいるくすりとののみあわせについて、そうだんしたいです。",
    "ex_cn": "我想咨询一下，这和我目前服用的药是否适合一起服用。",
    "id": 20214,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "副作用",
    "reading": "ふくさよう",
    "meaning": "副作用",
    "type": "名",
    "level": "n3",
    "ex_jp": "副作用についての説明を、もう一度聞かせてください。",
    "ex_read": "ふくさようについてのせつめいを、もういちどきかせてください。",
    "ex_cn": "请再为我说明一遍有关副作用的内容。",
    "id": 20215,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "服用中",
    "reading": "ふくようちゅう",
    "meaning": "正在服用",
    "type": "名",
    "level": "n3",
    "ex_jp": "服用中の薬の名前を、紙に書いて持ってきました。",
    "ex_read": "ふくようちゅうのくすりのなまえを、かみにかいてもってきました。",
    "ex_cn": "我把正在服用的药名写在纸上带来了。",
    "id": 20216,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "使用期限",
    "reading": "しようきげん",
    "meaning": "使用期限；有效期",
    "type": "名",
    "level": "n3",
    "ex_jp": "使用期限は、箱のどこに書いてありますか。",
    "ex_read": "しようきげんは、はこのどこにかいてありますか。",
    "ex_cn": "有效期写在盒子的哪里？",
    "id": 20217,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "薬の受け取り",
    "reading": "くすりのうけとり",
    "meaning": "取药；领取药品",
    "type": "名",
    "level": "n4",
    "ex_jp": "薬の受け取りに来ました。名前はこちらです。",
    "ex_read": "くすりのうけとりにきました。なまえはこちらです。",
    "ex_cn": "我是来取药的。这是我的姓名。",
    "id": 20218,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "眠気が出る",
    "reading": "ねむけがでる",
    "meaning": "产生困意；犯困",
    "type": "表达",
    "level": "n3",
    "ex_jp": "この薬で眠気が出ることはありますか。",
    "ex_read": "このくすりでねむけがでることはありますか。",
    "ex_cn": "这种药会让人犯困吗？",
    "id": 20219,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "pharmacy",
    "word": "説明書",
    "reading": "せつめいしょ",
    "meaning": "说明书",
    "type": "名",
    "level": "n4",
    "ex_jp": "薬の説明書をなくしたので、もう一枚いただけますか。",
    "ex_read": "くすりのせつめいしょをなくしたので、もういちまいいただけますか。",
    "ex_cn": "我把药品说明书弄丢了，可以再给我一份吗？",
    "id": 20220,
    "topicId": "health",
    "category": "药店取药",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "助けてください",
    "reading": "たすけてください",
    "meaning": "请帮帮我；救命",
    "type": "表达",
    "level": "n5",
    "ex_jp": "助けてください。友達がけがをしました。",
    "ex_read": "たすけてください。ともだちがけがをしました。",
    "ex_cn": "请帮帮我，我朋友受伤了。",
    "id": 20221,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "救急車",
    "reading": "きゅうきゅうしゃ",
    "meaning": "救护车",
    "type": "名",
    "level": "n4",
    "ex_jp": "救急車を呼んでいただけますか。",
    "ex_read": "きゅうきゅうしゃをよんでいただけますか。",
    "ex_cn": "可以请您叫一辆救护车吗？",
    "id": 20222,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "現在地",
    "reading": "げんざいち",
    "meaning": "当前位置",
    "type": "名",
    "level": "n3",
    "ex_jp": "現在地を説明したいのですが、住所が分かりません。",
    "ex_read": "げんざいちをせつめいしたいのですが、じゅうしょがわかりません。",
    "ex_cn": "我想说明现在的位置，但不知道地址。",
    "id": 20223,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "目印",
    "reading": "めじるし",
    "meaning": "标志物；辨认位置的标记",
    "type": "名",
    "level": "n3",
    "ex_jp": "近くの目印は、大きな時計のある建物です。",
    "ex_read": "ちかくのめじるしは、おおきなとけいのあるたてものです。",
    "ex_cn": "附近的标志物是一栋有大钟的建筑。",
    "id": 20224,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "緊急連絡先",
    "reading": "きんきゅうれんらくさき",
    "meaning": "紧急联系人及联系方式",
    "type": "名",
    "level": "n3",
    "ex_jp": "緊急連絡先は、かばんの中のカードに書いてあります。",
    "ex_read": "きんきゅうれんらくさきは、かばんのなかのカードにかいてあります。",
    "ex_cn": "紧急联系人的信息写在包里的卡片上。",
    "id": 20225,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "安否確認",
    "reading": "あんぴかくにん",
    "meaning": "确认是否平安",
    "type": "名",
    "level": "n2",
    "ex_jp": "家族の安否確認ができず、心配しています。",
    "ex_read": "かぞくのあんぴかくにんができず、しんぱいしています。",
    "ex_cn": "我还无法确认家人是否平安，非常担心。",
    "id": 20226,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "身分証明書",
    "reading": "みぶんしょうめいしょ",
    "meaning": "身份证明文件",
    "type": "名",
    "level": "n3",
    "ex_jp": "身分証明書が入った財布をなくしました。",
    "ex_read": "みぶんしょうめいしょがはいったさいふをなくしました。",
    "ex_cn": "我把装有身份证明文件的钱包弄丢了。",
    "id": 20227,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "落とし物",
    "reading": "おとしもの",
    "meaning": "遗失物品；失物",
    "type": "名",
    "level": "n4",
    "ex_jp": "落とし物の問い合わせは、こちらでできますか。",
    "ex_read": "おとしもののといあわせは、こちらでできますか。",
    "ex_cn": "这里可以查询失物吗？",
    "id": 20228,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "盗難届",
    "reading": "とうなんとどけ",
    "meaning": "失窃报案；失窃报案登记",
    "type": "名",
    "level": "n3",
    "ex_jp": "自転車が盗まれたので、盗難届を出したいです。",
    "ex_read": "じてんしゃがぬすまれたので、とうなんとどけをだしたいです。",
    "ex_cn": "我的自行车被偷了，想登记报案。",
    "id": 20229,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "emergency",
    "word": "日本語がうまく話せません",
    "reading": "にほんごがうまくはなせません",
    "meaning": "我的日语说得不太好",
    "type": "表达",
    "level": "n4",
    "ex_jp": "日本語がうまく話せません。ゆっくり質問していただけますか。",
    "ex_read": "にほんごがうまくはなせません。ゆっくりしつもんしていただけますか。",
    "ex_cn": "我的日语说得不太好，可以请您慢一点问吗？",
    "id": 20230,
    "topicId": "services",
    "category": "紧急求助",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "避難所",
    "reading": "ひなんじょ",
    "meaning": "避难所",
    "type": "名",
    "level": "n3",
    "ex_jp": "この避難所について、中国語の案内はありますか。",
    "ex_read": "このひなんじょについて、ちゅうごくごのあんないはありますか。",
    "ex_cn": "关于这个避难所，有中文说明吗？",
    "id": 20231,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "避難場所",
    "reading": "ひなんばしょ",
    "meaning": "避难地点",
    "type": "名",
    "level": "n3",
    "ex_jp": "地図に書かれた避難場所の名前が読めません。",
    "ex_read": "ちずにかかれたひなんばしょのなまえがよめません。",
    "ex_cn": "我不会读地图上标出的避难地点名称。",
    "id": 20232,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "防災訓練",
    "reading": "ぼうさいくんれん",
    "meaning": "防灾演练",
    "type": "名",
    "level": "n3",
    "ex_jp": "町の防災訓練に、初めて参加しました。",
    "ex_read": "まちのぼうさいくんれんに、はじめてさんかしました。",
    "ex_cn": "我第一次参加了社区的防灾演练。",
    "id": 20233,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "非常持ち出し袋",
    "reading": "ひじょうもちだしぶくろ",
    "meaning": "紧急避难携带包",
    "type": "名",
    "level": "n3",
    "ex_jp": "防災教室で、非常持ち出し袋の展示を見ました。",
    "ex_read": "ぼうさいきょうしつで、ひじょうもちだしぶくろのてんじをみました。",
    "ex_cn": "我在防灾课堂上看到了应急避难包的展示。",
    "id": 20234,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "断水",
    "reading": "だんすい",
    "meaning": "停水",
    "type": "名",
    "level": "n3",
    "ex_jp": "断水のお知らせが届きましたが、内容を確認したいです。",
    "ex_read": "だんすいのおしらせがとどきましたが、ないようをかくにんしたいです。",
    "ex_cn": "我收到了停水通知，想确认一下内容。",
    "id": 20235,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "停電",
    "reading": "ていでん",
    "meaning": "停电",
    "type": "名",
    "level": "n4",
    "ex_jp": "停電で、部屋の明かりが消えました。",
    "ex_read": "ていでんで、へやのあかりがきえました。",
    "ex_cn": "因为停电，房间里的灯熄灭了。",
    "id": 20236,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "給水所",
    "reading": "きゅうすいじょ",
    "meaning": "供水点",
    "type": "名",
    "level": "n3",
    "ex_jp": "給水所の案内は、どこで確認できますか。",
    "ex_read": "きゅうすいじょのあんないは、どこでかくにんできますか。",
    "ex_cn": "在哪里可以查看供水点的信息？",
    "id": 20237,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "余震",
    "reading": "よしん",
    "meaning": "余震",
    "type": "名",
    "level": "n3",
    "ex_jp": "余震が続いているというニュースを見ました。",
    "ex_read": "よしんがつづいているというニュースをみました。",
    "ex_cn": "我看到了余震仍在持续的新闻。",
    "id": 20238,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "支援物資",
    "reading": "しえんぶっし",
    "meaning": "救援物资；援助物资",
    "type": "名",
    "level": "n3",
    "ex_jp": "支援物資について、受付で説明を聞きました。",
    "ex_read": "しえんぶっしについて、うけつけでせつめいをききました。",
    "ex_cn": "我在服务台听取了有关救援物资的说明。",
    "id": 20239,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  },
  {
    "sceneId": "disaster",
    "word": "多言語対応",
    "reading": "たげんごたいおう",
    "meaning": "多语言服务；支持多种语言",
    "type": "名",
    "level": "n3",
    "ex_jp": "この相談窓口は、多言語対応ですか。",
    "ex_read": "このそうだんまどぐちは、たげんごたいおうですか。",
    "ex_cn": "这个咨询窗口提供多语言服务吗？",
    "id": 20240,
    "topicId": "nature",
    "category": "防灾避难",
    "appear": 0,
    "years": [],
    "ex_extra": [],
    "note": "场景词句；等级为本站学习难度参考。"
  }
];
if (typeof VOCAB_DATA !== 'undefined') VOCAB_DATA.push(...SCENE_VOCAB);
if (typeof module !== 'undefined' && module.exports) module.exports = SCENE_VOCAB;
